# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.


# Site Settings
locale                   : "en-US"
title                    : "Ameya Harmalkar"
title_separator          : " | "
name                     : "Ameya Harmalkar"
description              : "Ameya Homepage"
url                      : "https://AmeyaHarmalkar.github.io"
baseurl                  : # the subpath of your site,
repository               : "AmeyaHarmalkar/AmeyaHarmalkar.github.io"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
breadcrumbs              : false # true, false (default)
words_per_minute         : 200
profilepic		 : #'/images/tzuehlke.jpg'
bkimage			 : #'/images/bk1.jpg'
#google_analytics: UA-XXXXXX-X
#font_awesome: 'XXXXXXXXXX.js'
author:
  name: 'Ameya Harmalkar'
  email: ameya@jhu.edu
  twitter_username: AmeyaHarmalkar
#  facebook_username: joshgerdes
  github_username:  AmeyaHarmalkar
#  linkedin_username:  thomas-zühlke-889182165
#  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
